name: gymbuddy_github
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  flutter_slidable: ^3.1.1
  hive: ^2.2.3
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/mountain_climber.jpg
    - assets/biceps.jpg
    - assets/dorsals.jpg
    - assets/legs.jpg
    - assets/shoulders.png
  uses-material-design: true
